[package]
name = "notes-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
ulid.workspace = true
sha2.workspace = true
thiserror.workspace = true
